name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  svg_flutter: ^0.0.1
  dots_indicator: ^4.0.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.1
  firebase_core: ^4.1.1
  dartz: ^0.10.1
  firebase_auth: ^6.1.0
  flutter_bloc: ^9.0.0
  get_it: ^7.7.0
  modal_progress_hud_nsn: ^0.5.1
  logger: ^2.3.0
  google_sign_in: '^6.2.1'
  flutter_facebook_auth: '^7.0.0'
  cloud_firestore: ^6.0.3
  skeletons: 0.0.3


  flutter_svg_provider: ^1.0.7
  font_awesome_flutter: ^10.9.1
  provider: ^6.1.5+1
  flutter_paypal_payment: ^1.0.8


dev_dependencies:
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/bottomNav/
    - assets/images/bottomNav/bold/


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_gen:
  output: lib/core/utils/gen
